### ISSUE TITLE
Implement IntervalMonthDayNano scalar conversion in DataFusion Unparser

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1580] opened 2024-06-02 07:32 UTC
**Describe the bug**
The unparser code in DataFusion (responsible for turning LogicalPlans back into SQL statements) does not handle IntervalMonthDayNano scalar values, which causes several of the TPC-H queries to fail with the following error:
`Error: "query tpch_q4 to results: External error: This feature is not implemented: Unsupported scalar: IntervalMonthDayNano(\"237684487542793012780631851008\")"`

The relevant code that needs to be implemented:
https://github.com/apache/datafusion/blob/1db3263497532fda5167386781755463f53c00a4/datafusion/sql/src/unparser/expr.rs#L802

This affects the following benchmark queries:
- `tpch_q4`

**Comment by phillipleblanc** [comment] 2024-06-05 06:35
Filed https://github.com/apache/datafusion/issues/10795 to track on the DataFusion side.

**Comment by y-f-u** [comment] 2024-06-19 06:45
The upstream fix is done, will create a new spiceai fork branch and merge relative stuff in.

**Comment by y-f-u** [comment] 2024-06-24 06:14
The upstream fix is merged, however, the issue is still not fixed for affected `bench` tests, as the str unparsed from this is `interval '1 mons'` which is not supported by dremio connector.

**Comment by y-f-u** [comment] 2024-06-24 06:17
Closed this to open a more specific one for failing bench in dremio.

**Closed as completed** 2024-06-24 06:17 UTC
Labels: kind/bug
