### ISSUE TITLE
Bug: SQLite accelerator doesn't support subquery definition in TPCH Q13

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2369] opened 2024-08-26 06:43 UTC
**Describe the bug**

A complex LEFT JOIN in TPCH Q13 is re-written as:

```sql
FROM customer LEFT JOIN orders ON ((customer.c_custkey = orders.o_custkey) AND orders.o_comment NOT LIKE '%special%requests%')
```

Running this query with SQLite acceleration federation results in a query error.

**To Reproduce**

1. Configure TPCH connectors with SQLite accelerator (with federation enabled)
2. Run TPCH Q13
3. Observe query failure

**Expected behavior**

Query should run successfully.

**Comment by sgrebnov** [comment] 2024-09-04 02:25
The issue is related not to complex joins but lack of support of subquery aliasing and  columns naming. Similar to question: https://stackoverflow.com/questions/57384028/subquery-with-alias-in-sqlite

The following generated JOIN sql works

```sql
SELECT * FROM customer LEFT JOIN orders ON ((customer.c_custkey = orders.o_custkey) AND orders.o_comment NOT LIKE '%special%requests%')
``` 

But the following part needs to be rewritten  - ` as c_orders (c_custkey, c_count)`


```sql
(
	SELECT
		`customer`.`c_custkey`,
		count(`orders`.`o_orderkey`)
	FROM
		`customer`
	LEFT JOIN `orders` ON
		((`customer`.`c_custkey` = `orders`.`o_custkey`)
			AND `orders`.`o_comment` NOT LIKE CAST('%special%requests%' AS TEXT))
	GROUP BY
		`customer`.`c_custkey`) AS `c_orders` (c_custkey,
	c_count)
```

```sql
(
	SELECT
		`customer`.`c_custkey` as c_custkey,
		count(`orders`.`o_orderkey`) as c_count
	FROM
		`customer`
	LEFT JOIN `orders` ON
		((`customer`.`c_custkey` = `orders`.`o_custkey`)
			AND `orders`.`o_comment` NOT LIKE CAST('%special%requests%' AS TEXT))
	GROUP BY
		`customer`.`c_custkey`) AS `c_orders`
```

**Comment by sgrebnov** [comment] 2024-09-05 04:15
Addressed by the following PR https://github.com/spiceai/spiceai/pull/2532

```sql
sql> select
    c_count,
    count(*) as custdist
from
    (
        select
            c_custkey,
            count(o_orderkey)
        from
            customer left outer join orders on
                        c_custkey = o_custkey
                    and o_comment not like '%special%requests%'
        group by
            c_custkey
    ) as c_orders (c_custkey, c_count)
group by
    c_count
order by
    custdist desc,
    c_count desc;
+---------+----------+
| c_count | custdist |
+---------+----------+
| 0       | 500      |
| 11      | 68       |
| 10      | 64       |
| 12      | 62       |
| 9       | 62       |
| 8       | 61       |
| 14      | 54       |
| 13      | 52       |
| 7       | 49       |
| 20      | 48       |
| 21      | 47       |
| 16      | 46       |
| 15      | 45       |
| 19      | 44       |
| 17      | 41       |
| 18      | 38       |
| 22      | 33       |
| 6       | 33       |
| 24      | 30       |
| 23      | 27       |
| 25      | 21       |
| 27      | 17       |
| 26      | 15       |
| 5       | 14       |
| 28      | 6        |
| 4       | 6        |
| 32      | 5        |
| 29      | 5        |
| 30      | 2        |
| 3       | 2        |
| 31      | 1        |
| 2       | 1        |
| 1       | 1        |
+---------+----------+

Time: 0.041224625 seconds. 33 rows.
```

**Closed as completed** 2024-09-05 04:30 UTC
Labels: kind/bug
