### ISSUE TITLE
Enhancement: Clickhouse `connection_timeout` should support the same formats as other time-based parameters

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3539] opened 2024-11-18 22:09 UTC
## Goal-State/What/Result

The `connection_timeout` parameter of the Clickhouse connector supports the same kind of time interval strings as other connectors.

## Why/Purpose

To create a consistent user experience.

## By When

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [ ] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Specification

_Provide a basic specification of the enhancement._

### Security Review

_Provide threat model and security review._

## How/Plan

_A clear and concise plan of how this should be implemented._

As mentioned by @phillipleblanc in https://github.com/spiceai/docs/pull/604

**Comment by phillipleblanc** [comment] 2024-11-28 03:59
Duplicate of #3710

**Closed as not planned by phillipleblanc** 2024-11-28 03:59 UTC
