### ISSUE TITLE
Snowflake quickstart Unsupported scalar: IntervalMonthDayNano(\"1660206966633859645440\")

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1529] opened 2024-05-27 22:21 UTC
**Describe the bug**
When I follow [Snowflake quickstart](https://github.com/spiceai/quickstarts/tree/trunk/snowflake) there is the following error when I run TPC-H test query

>Error An internal error occurred. Execute '.error' to show details.
sql> .error
Status { code: Internal, message: "Unable to collect results after query execution: This feature is not implemented: Unsupported scalar: IntervalMonthDayNano(\"1660206966633859645440\")", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 27 May 2024 22:14:32 GMT", "content-length": "0"} }, source: None }

**Comment by phillipleblanc** [comment] 2024-06-04 03:02
Duplicate of #1580

**Closed as not planned by phillipleblanc** 2024-06-04 03:02 UTC
Labels: kind/bug
