### ISSUE TITLE
Changing S3 url after starting runtime doesn't report that it couldn't load the dataset

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#953] opened 2024-03-27 01:11 UTC
**Describe the bug**
I followed the quickstart for the S3 data connector.  After setting up the bucket using spice dataset configure.  I modified the dataset url to an invalid url:

from: s3://wewespiceai-demo-datasets/taxi_trips/2024/abcd

The runtime reloads and reports that it unloaded the dataset, and then reloaded it.  But it doesn't do so successfully.  

Show tables doesn't show the taxi_trips tables any more.  The runtime continutes to refresh.

**To Reproduce**

Follow quickstart for s3 connector.  After configuring dataset, change the S3 url to an invalid url.

**Expected behavior**
An error that the dataset couldn't be loaded.  No refreshing message about the dataset.

**Screenshots**

**Additional context**

**Comment by digadeesh** [comment] 2024-03-27 01:37
Test with other data sources.  May not be only S3.

**Comment by gloomweaver** [comment] 2024-04-30 15:07
s3 doesn't reproduce
![CleanShot 2024-04-30 at 7  05 35@2x](https://github.com/spiceai/spiceai/assets/20399045/2b3c64e6-a66a-4760-804a-6f251e90c2bf)

**Comment by ewgenius** [comment] 2024-05-03 15:40
@digadeesh I can't reproduce that anymore for s3, for accelerated and non-accelerated datasets

quickstart:

https://github.com/spiceai/spiceai/assets/827338/2bc0b496-6f55-4521-8c9f-edc0ffc4d391

https://github.com/spiceai/spiceai/assets/827338/bbd045b9-4102-4c28-be7a-15b6d70a936f

**Comment by ewgenius** [comment] 2024-05-03 23:37
Was partially fixed by https://github.com/spiceai/spiceai/pull/1126

**Closed as not planned** 2024-05-03 23:40 UTC
Labels: kind/bug
