### ISSUE TITLE
DuckDB accelerator and connector return no results in TPCH Q11

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2519] opened 2024-09-04 23:38 UTC
**Describe the bug**

When running TPCH Q11 with DuckDB as either a connector or an accelerator, it returns `No results`.

Running TPCH Q11 on the native DuckDB CLI also returns 0 rows.

```
┌────────────┬───────────────┐
│ ps_partkey │     value     │
│   int64    │ decimal(38,2) │
├────────────┴───────────────┤
│           0 rows           │
└────────────────────────────┘
```

**To Reproduce**

1. Configure TPCH data source as either connector or accelerator
2. Run TPCH Q11
3. See behavior

**Expected behavior**

The query should return rows as expected by TPCH.

**Comment by peasee** [comment] 2024-09-05 00:40
Running with a smaller scale factor (1) on the native DuckDB CLI returns results:

```
┌────────────┬───────────────┐
│ ps_partkey │     value     │
│   int64    │ decimal(38,2) │
├────────────┼───────────────┤
│     129760 │   17538456.86 │
│     166726 │   16503353.92 │
│     191287 │   16474801.97 │
│     161758 │   16101755.54 │
│      34452 │   15983844.72 │
│     139035 │   15907078.34 │
│       9403 │   15451755.62 │
│     154358 │   15212937.88 │
│      38823 │   15064802.86 │
│      85606 │   15053957.15 │
│      33354 │   14408297.40 │
│     154747 │   14407580.68 │
│      82865 │   14235489.78 │
│      76094 │   14094247.04 │
│        222 │   13937777.74 │
│     121271 │   13908336.00 │
│      55221 │   13716120.47 │
│      22819 │   13666434.28 │
│      76281 │   13646853.68 │
│      85298 │   13581154.93 │
│        ·   │         ·     │
│        ·   │         ·     │
│        ·   │         ·     │
│      36289 │    7901946.50 │
│      61739 │    7900794.00 │
│      52338 │    7898638.08 │
│     194299 │    7898421.24 │
│     105235 │    7897829.94 │
│      77207 │    7897752.72 │
│      96712 │    7897575.27 │
│      10157 │    7897046.25 │
│     171154 │    7896814.50 │
│      79373 │    7896186.00 │
│     113808 │    7893353.88 │
│      27901 │    7892952.00 │
│     128820 │    7892882.72 │
│      25891 │    7890511.20 │
│     122819 │    7888881.02 │
│     154731 │    7888301.33 │
│     101674 │    7879324.60 │
│      51968 │    7879102.21 │
│      72073 │    7877736.11 │
│       5182 │    7874521.73 │
├────────────┴───────────────┤
│    1048 rows (40 shown)    │
└────────────────────────────┘
```

Running with the Spice Runtime returns `No results`.

**Comment by peasee** [comment] 2024-09-05 06:24
Memory mode succeeds and returns results as expected. SQLite doesn't seem to be affected as it succeeds in both memory and file mode.

**Comment by phillipleblanc** [comment] 2024-09-09 00:22
Duplicate of #2518

**Closed as not planned by phillipleblanc** 2024-09-09 00:22 UTC
Labels: kind/bug
