### ISSUE TITLE
Bug: Query Error Expected: joined table, found: ,

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2616] opened 2024-09-11 23:07 UTC
## Describe the bug

* Run TPCDS query 21 using a connector with DuckDB and accelerator with Postgres give the error
* When running TPCDS Q21 using a connector with DuckDB in-memory or file-mode acceleration, observe the following error:

```
Query Error Expected: joined table, found: ,
```

As seen from TPCDS queries in [datafusion-benchmarks](https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries)

## To Reproduce

1. Configure a connector with a TPCDS data source using DuckDB in-memory or file-mode acceleration
2. Run TPCDS Q21
3. See error

## Expected behavior

The query should run as expected.

## Testing Validation

- [ ] Q21 in-memory DuckDB
- [ ] Q21 file-mode DuckDB

## Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: tpcds1.duckdb
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
```

spicepod.yaml
```
version: v1beta1
kind: Spicepod
name: tpcds-sf0.1.db
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds

```

**Comment by sgrebnov** [comment] 2024-10-02 02:10
The issue is related to invalid syntax around `+- 30 days` which is unsupported by both Postgres native and Datafusion so parser is failing. Updating to `interval '30 days'` fixes this. Note: error message could be improved but consider this as low priority, closing this issue.

Before

```sql
select  *
 from(select w_warehouse_name
            ,i_item_id
            ,sum(case when (cast(d_date as date) < cast ('2000-05-19' as date))
	                then inv_quantity_on_hand 
                      else 0 end) as inv_before
            ,sum(case when (cast(d_date as date) >= cast ('2000-05-19' as date))
                      then inv_quantity_on_hand 
                      else 0 end) as inv_after
   from inventory
       ,warehouse
       ,item
       ,date_dim
   where i_current_price between 0.99 and 1.49
     and i_item_sk          = inv_item_sk
     and inv_warehouse_sk   = w_warehouse_sk
     and inv_date_sk    = d_date_sk
     and d_date between (cast ('2000-05-19' as date) - 30 days)
                    and (cast ('2000-05-19' as date) + 30 days)
   group by w_warehouse_name, i_item_id) x
 where (case when inv_before > 0 
             then inv_after / inv_before 
             else null
             end) between 2.0/3.0 and 3.0/2.0
 order by w_warehouse_name
         ,i_item_id
  LIMIT 100;
```

After

```sql
select  *
 from(select w_warehouse_name
            ,i_item_id
            ,sum(case when (cast(d_date as date) < cast ('2000-05-19' as date))
	                then inv_quantity_on_hand 
                      else 0 end) as inv_before
            ,sum(case when (cast(d_date as date) >= cast ('2000-05-19' as date))
                      then inv_quantity_on_hand 
                      else 0 end) as inv_after
   from inventory
       ,warehouse
       ,item
       ,date_dim
   where i_current_price between 0.99 and 1.49
     and i_item_sk          = inv_item_sk
     and inv_warehouse_sk   = w_warehouse_sk
     and inv_date_sk    = d_date_sk
     and d_date between (cast ('2000-05-19' as date) - interval '30 days')
                    and (cast ('2000-05-19' as date) + interval '30 days')
   group by w_warehouse_name, i_item_id) x
 where (case when inv_before > 0 
             then inv_after / inv_before 
             else null
             end) between 2.0/3.0 and 3.0/2.0
 order by w_warehouse_name
         ,i_item_id
  LIMIT 100;
```

```shell
+---------------------+------------------+------------+-----------+
| w_warehouse_name    | i_item_id        | inv_before | inv_after |
+---------------------+------------------+------------+-----------+
| Conventional childr | AAAAAAAAHDAAAAAA | 2171       | 2759      |
| Conventional childr | AAAAAAAAMBAAAAAA | 2427       | 2495      |
| Conventional childr | AAAAAAAAPKAAAAAA | 2319       | 2866      |
+---------------------+------------------+------------+-----------+

Time: 0.073570333 seconds. 3 rows.
```

**Closed as completed by sgrebnov** 2024-10-02 02:10 UTC
Labels: kind/bug, area/data-accelerators
