### ISSUE TITLE
Bug: SQLite accelerator returns different data comparing to source data connector

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1282] opened 2024-05-02 05:19 UTC
**Describe the bug**
Using SQLite accelerator and MySQL data connector to accelerate data similar to attach screenshot, some of the data are difference to the source.

**To Reproduce**
As described.

**Expected behavior**
Data can be either unsupported to accelerate, or the correctness need to be ensured.

**Screenshots**

<img width="742" alt="Screenshot 2024-05-01 at 10 56 38" src="https://github.com/spiceai/spiceai/assets/561715/6085c108-5eaa-4409-80c4-d4b9b6b3ffcf">

**Comment by gloomweaver** [comment] 2024-05-04 01:17
Could not reproduce this same data
Could you provide create and insert statements for this
![CleanShot 2024-05-04 at 5  20 51@2x](https://github.com/spiceai/spiceai/assets/20399045/c97fe4f3-4363-48a1-99be-cc8980972fd9)
?

**Comment by y-f-u** [comment] 2024-05-16 04:21
So this might be fixed by https://github.com/spiceai/spiceai/pull/1261/files.
Time is matching ...

**Comment by digadeesh** [comment] 2024-05-16 19:26
Will resolve given we fixed with the referenced PR.

**Closed as completed by digadeesh** 2024-05-16 19:26 UTC
Labels: kind/bug
